services:
  web:
    container_name: core-web-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEPLOYMENT_ENV: staging
        NEXT_PUBLIC_ACCOUNTING_BASE_URL: ${NEXT_PUBLIC_ACCOUNTING_BASE_URL}
        NEXT_PUBLIC_BLUE_NAAS_URL: ${NEXT_PUBLIC_BLUE_NAAS_URL}
        NEXT_PUBLIC_SMALL_SCALE_SIMULATOR_URL: ${NEXT_PUBLIC_SMALL_SCALE_SIMULATOR_URL}
        NEXT_PUBLIC_CELL_SVC_BASE_URL: ${NEXT_PUBLIC_CELL_SVC_BASE_URL}
        NEXT_PUBLIC_THUMBNAIL_GENERATION_BASE_URL: ${NEXT_PUBLIC_THUMBNAIL_GENERATION_BASE_URL}
        NEXT_PUBLIC_ME_MODEL_ANALYSIS_WS_URL: ${NEXT_PUBLIC_ME_MODEL_ANALYSIS_WS_URL}
        NEXT_PUBLIC_VIRTUAL_LAB_API_URL: ${NEXT_PUBLIC_VIRTUAL_LAB_API_URL}
        NEXT_PUBLIC_NOTEBOOK_SERVICE_BASE_URL: ${NEXT_PUBLIC_NOTEBOOK_SERVICE_BASE_URL}
        NEXT_PUBLIC_OBI_ONE_URL: ${NEXT_PUBLIC_OBI_ONE_URL}
        NEXT_PUBLIC_MATOMO_URL: ${NEXT_PUBLIC_MATOMO_URL}
        NEXT_PUBLIC_MATOMO_CDN_URL: ${NEXT_PUBLIC_MATOMO_CDN_URL}
        NEXT_PUBLIC_MATOMO_SITE_ID: ${NEXT_PUBLIC_MATOMO_SITE_ID}
        NEXT_PUBLIC_DEPLOYMENT_ENV: ${NEXT_PUBLIC_DEPLOYMENT_ENV}
        PRIMARY_HOSTNAME: ${PRIMARY_HOSTNAME}
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
        NEXT_PUBLIC_AI_AGENT_URL: ${NEXT_PUBLIC_AI_AGENT_URL}
        NEXT_PUBLIC_ENABLE_RUN_NOTEBOOK: ${NEXT_PUBLIC_ENABLE_RUN_NOTEBOOK}
        NEXT_PUBLIC_ENTITY_CORE_URL: ${NEXT_PUBLIC_ENTITY_CORE_URL}
        NEXT_PUBLIC_ENTITY_CORE_PUBLIC_VIRTUAL_LAB_ID: ${NEXT_PUBLIC_ENTITY_CORE_PUBLIC_VIRTUAL_LAB_ID}
        NEXT_PUBLIC_ENTITY_CORE_PUBLIC_PROJECT_ID: ${NEXT_PUBLIC_ENTITY_CORE_PUBLIC_PROJECT_ID}
        NEXT_PUBLIC_DEFAULT_BRAIN_REGION_HIERARCHY_ID: ${NEXT_PUBLIC_DEFAULT_BRAIN_REGION_HIERARCHY_ID}
        NEXT_PUBLIC_DEFAULT_SELECTED_BRAIN_REGION_ID: ${NEXT_PUBLIC_DEFAULT_SELECTED_BRAIN_REGION_ID}
        NEXT_PUBLIC_BASIC_CELL_GROUPS_AND_REGIONS_BRAIN_REGION_ANNOTATION_VALUE: ${NEXT_PUBLIC_BASIC_CELL_GROUPS_AND_REGIONS_BRAIN_REGION_ANNOTATION_VALUE}
        NEXT_PUBLIC_DEFAULT_BRAIN_ATLAS_ID: ${NEXT_PUBLIC_DEFAULT_BRAIN_ATLAS_ID}
        NEXT_PUBLIC_ROOT_BRAIN_REGION_ID: ${NEXT_PUBLIC_ROOT_BRAIN_REGION_ID}
        NEXT_PUBLIC_ROOT_BRAIN_REGION_ANNOTATION_VALUE: ${NEXT_PUBLIC_ROOT_BRAIN_REGION_ANNOTATION_VALUE}
        NEXT_PUBLIC_LEGACY_DEFAULT_CIRCUIT_ID: ${NEXT_PUBLIC_LEGACY_DEFAULT_CIRCUIT_ID}
        NEXT_PUBLIC_CELL_COMPOSITION_ID: ${NEXT_PUBLIC_CELL_COMPOSITION_ID}
        KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        MAILCHIMP_API_KEY: ${MAILCHIMP_API_KEY}
        MAILCHIMP_AUDIENCE_ID: ${MAILCHIMP_AUDIENCE_ID}
        MAILCHIMP_API_SERVER: ${MAILCHIMP_API_SERVER}

    ports:
      - '3000:8000'
    env_file:
      - .env.local
    restart: unless-stopped
