services:
  web:
    container_name: core-web-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-latest}
    ports:
      - "3000:8000"
    env_file:
      - .env
      - .env.development
      - .env.development.local
    restart: unless-stopped
