allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  es5-ext: true
  esbuild: true
  lefthook: true
  sharp: true

minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - '@openbraininstitute/*'
  - '@tolokoban/tgd'
  - cnfast@0.0.8
blockExoticSubdeps: true
verifyDepsBeforeRun: error
