allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  es5-ext: true
  esbuild: true
  lefthook: true
  sharp: true
blockExoticSubdeps: true

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@openbraininstitute/*'
  - '@tolokoban/tgd'
  - storybook
  - '@storybook/*'
  - eslint-plugin-storybook
  - '@chromatic-com/storybook'
minimumReleaseAgeStrict: true
verifyDepsBeforeRun: error
