const singleShowcaseQuery = (
  slug: string,
) => `*[_type == "publicProjects" && slug.current == "${slug}"][0] {
    name,
    'slug': slug.current,
    authorsList,
    introduction,
    _updatedAt,
    'heroImage': heroImage.asset->url,
    description,
    videosList[] {
      url,
      title,
      alt,
      hasCaption,
      useTimestamps,
      'captionTrack': captionTrack.asset->url
    },
    artifactType[],
    artifact[] {
      title, 
      description,
      "file": file.asset->url,
      url,
      _type,
    },
    meModelsList[] {
      'file': file.asset->url,
      name,
      hasMorphologyThumbnail,
      "morphology": morphology.asset->url,
      hasTraceThumbnail,
      "trace": trace.asset->url,
      validated,
      brainRegion,
      species,
      mType,
      eType,
      createdBy,
      creationDate,
      morphologyId,
      traceFileId,
      url,
      _type,
    },
    minimalMeModel[] {
      name,
      brainRegion,
      mType,
      eType,
      species,
    },
    eModelsList[] {
      name,
      hasResponseThumbnail,
      'response': response.asset->url,
      brainRegion,
      mType,
      eType,
      morphologyName,
      modelCumulatedScore,
      species,
      validated,
      contributor,
      creationDate,
    },
    eModelTable[] {
      name,
      'response': response.asset -> url,
      brainRegion,
      mType,
      eType,
      morphology,
      modelCumulatedScore,
      species,
      contributors,
      creationDate,
      downloadLink,
      download
    },
    meModelTable[] {
      name,
      'morphologyThumbnail': morphologyThumbnail.asset -> url,
      'traceThumbnail': traceThumbnail.asset -> url,
      validated,
      brainRegion,
      mType,
      eType,
      species,
      createdBy,
      creationDate,
      download
    },
    notebook[] {
      name,
      description,
      objectOfInterest,
      scale,
      authors,
      creationDate,
      readMe,
      url,
    },
    synaptomeTable[] {
      name,
      description,
      MEModel,
      MType,
      EType,
      brainRegion,
      species,
      createdBy,
      creationDate,
      download,
    },
    _updatedAt,
  }`;

export default singleShowcaseQuery;
