import { CircuitSchemaProps } from '../type';

const HARD_CODED_CONTENT: CircuitSchemaProps[] = [
  {
    key: 'nbS1-O1',
    name: 'nbS1-O1',
    description: 'Central subvolume of nbS1 (do we know the volume or a percentage?)',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457567,
    numberOfSynapses: 407127134,
    metadata: {
      contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'November, 2024',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1/connectivity_matrix.h5',
        key: 'nbS1-O1_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0',
        name: 'nbS1-HEX0',
        description:
          'Hexagonal column at the center of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291147,
        numberOfSynapses: 41299369,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0/connectivity_matrix.h5',
            key: 'nbS1-HEX0_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX0-L1',
            name: 'nbS1-HEX0-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX0',
            parent: 'nbS1-HEX0',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 291,
            numberOfConnections: 676,
            numberOfSynapses: 10929,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX0-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX0-L23',
            name: 'nbS1-HEX0-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX0',
            parent: 'nbS1-HEX0',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8173,
            numberOfConnections: 974129,
            numberOfSynapses: 4310007,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX0-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX0-L4',
            name: 'nbS1-HEX0-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX0',
            parent: 'nbS1-HEX0',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 4870,
            numberOfConnections: 428070,
            numberOfSynapses: 2349346,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX0-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX0-L5',
            name: 'nbS1-HEX0-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX0',
            parent: 'nbS1-HEX0',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5824,
            numberOfConnections: 652761,
            numberOfSynapses: 5240656,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX0-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX0-L6',
            name: 'nbS1-HEX0-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX0',
            parent: 'nbS1-HEX0',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 11032,
            numberOfConnections: 1859140,
            numberOfSynapses: 8637407,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX0-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX1',
        name: 'nbS1-HEX1',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 29738,
        numberOfConnections: 8068909,
        numberOfSynapses: 40583896,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1/connectivity_matrix.h5',
            key: 'nbS1-HEX1_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX1-L1',
            name: 'nbS1-HEX1-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX1',
            parent: 'nbS1-HEX1',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 419,
            numberOfConnections: 1256,
            numberOfSynapses: 19527,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX1-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX1-L23',
            name: 'nbS1-HEX1-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX1',
            parent: 'nbS1-HEX1',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8552,
            numberOfConnections: 1058051,
            numberOfSynapses: 4750999,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX1-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX1-L4',
            name: 'nbS1-HEX1-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX1',
            parent: 'nbS1-HEX1',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 4767,
            numberOfConnections: 394797,
            numberOfSynapses: 2191351,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX1-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX1-L5',
            name: 'nbS1-HEX1-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX1',
            parent: 'nbS1-HEX1',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5818,
            numberOfConnections: 662748,
            numberOfSynapses: 5302359,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX1-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX1-L6',
            name: 'nbS1-HEX1-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX1',
            parent: 'nbS1-HEX1',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 10182,
            numberOfConnections: 1668716,
            numberOfSynapses: 7734906,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX1-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX1-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX2',
        name: 'nbS1-HEX2',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 31338,
        numberOfConnections: 8792594,
        numberOfSynapses: 43837756,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2/connectivity_matrix.h5',
            key: 'nbS1-HEX2_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX2-L1',
            name: 'nbS1-HEX2-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX2',
            parent: 'nbS1-HEX2',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 321,
            numberOfConnections: 791,
            numberOfSynapses: 12302,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX2-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX2-L23',
            name: 'nbS1-HEX2-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX2',
            parent: 'nbS1-HEX2',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8234,
            numberOfConnections: 1032044,
            numberOfSynapses: 4663990,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX2-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX2-L4',
            name: 'nbS1-HEX2-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX2',
            parent: 'nbS1-HEX2',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 4795,
            numberOfConnections: 417998,
            numberOfSynapses: 2317008,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX2-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX2-L5',
            name: 'nbS1-HEX2-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX2',
            parent: 'nbS1-HEX2',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5963,
            numberOfConnections: 682975,
            numberOfSynapses: 5446047,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX2-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX2-L6',
            name: 'nbS1-HEX2-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX2',
            parent: 'nbS1-HEX2',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 12025,
            numberOfConnections: 2116358,
            numberOfSynapses: 9815194,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX2-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX2-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX3',
        name: 'nbS1-HEX3',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 29892,
        numberOfConnections: 8214630,
        numberOfSynapses: 41465996,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3/connectivity_matrix.h5',
            key: 'nbS1-HEX3_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX3-L1',
            name: 'nbS1-HEX3-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX3',
            parent: 'nbS1-HEX3',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 364,
            numberOfConnections: 1085,
            numberOfSynapses: 17532,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX3-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX3-L23',
            name: 'nbS1-HEX3-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX3',
            parent: 'nbS1-HEX3',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8193,
            numberOfConnections: 1028669,
            numberOfSynapses: 4700826,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX3-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX3-L4',
            name: 'nbS1-HEX3-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX3',
            parent: 'nbS1-HEX3',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 4716,
            numberOfConnections: 394448,
            numberOfSynapses: 2190071,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX3-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX3-L5',
            name: 'nbS1-HEX3-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX3',
            parent: 'nbS1-HEX3',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5820,
            numberOfConnections: 672103,
            numberOfSynapses: 5369952,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX3-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX3-L6',
            name: 'nbS1-HEX3-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX3',
            parent: 'nbS1-HEX3',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 10799,
            numberOfConnections: 1848739,
            numberOfSynapses: 8652164,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX3-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX3-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: null,
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX4',
        name: 'nbS1-HEX4',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30249,
        numberOfConnections: 8195702,
        numberOfSynapses: 41439211,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4/connectivity_matrix.h5',
            key: 'nbS1-HEX4_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX4-L1',
            name: 'nbS1-HEX4-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX4',
            parent: 'nbS1-HEX4',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 478,
            numberOfConnections: 1469,
            numberOfSynapses: 23306,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX4-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX4-L23',
            name: 'nbS1-HEX4-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX4',
            parent: 'nbS1-HEX4',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 9265,
            numberOfConnections: 1183225,
            numberOfSynapses: 5332946,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX4-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX4-L4',
            name: 'nbS1-HEX4-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX4',
            parent: 'nbS1-HEX4',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5030,
            numberOfConnections: 423147,
            numberOfSynapses: 2328003,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX4-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX4-L5',
            name: 'nbS1-HEX4-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX4',
            parent: 'nbS1-HEX4',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5897,
            numberOfConnections: 674020,
            numberOfSynapses: 5282245,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX4-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX4-L6',
            name: 'nbS1-HEX4-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX4',
            parent: 'nbS1-HEX4',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 9579,
            numberOfConnections: 1539182,
            numberOfSynapses: 7281873,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX4-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX4-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: null,
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX5',
        name: 'nbS1-HEX5',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 29861,
        numberOfConnections: 8058699,
        numberOfSynapses: 40349070,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5/connectivity_matrix.h5',
            key: 'nbS1-HEX5_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX5-L1',
            name: 'nbS1-HEX5-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX5',
            parent: 'nbS1-HEX5',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 473,
            numberOfConnections: 1342,
            numberOfSynapses: 20958,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX5-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX5-L23',
            name: 'nbS1-HEX5-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX5',
            parent: 'nbS1-HEX5',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 9615,
            numberOfConnections: 1225208,
            numberOfSynapses: 5491261,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX5-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX5-L4',
            name: 'nbS1-HEX5-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX5',
            parent: 'nbS1-HEX5',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5183,
            numberOfConnections: 449007,
            numberOfSynapses: 2480015,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX5-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX5-L5',
            name: 'nbS1-HEX5-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX5',
            parent: 'nbS1-HEX5',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5658,
            numberOfConnections: 618772,
            numberOfSynapses: 4859081,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX5-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX5-L6',
            name: 'nbS1-HEX5-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX5',
            parent: 'nbS1-HEX5',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8932,
            numberOfConnections: 1408712,
            numberOfSynapses: 6671497,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX5-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX5-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: null,
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'nbS1-HEX6',
        name: 'nbS1-HEX6',
        description: 'Hexagonal column of nbS1-O1, part of a partition into seven columns.',
        parent: 'nbS1-O1',
        hasSubcircuits: true,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30444,
        numberOfConnections: 8406565,
        numberOfSynapses: 41943686,
        metadata: {
          contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6/connectivity_matrix.h5',
            key: 'nbS1-HEX6_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [
          {
            key: 'nbS1-HEX6-L1',
            name: 'nbS1-HEX6-L1',
            description: 'Neurons in layer 1 of the hexagonal column nbS1-O1-HEX6',
            parent: 'nbS1-HEX6',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 349,
            numberOfConnections: 881,
            numberOfSynapses: 13777,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6-L1/connectivity_matrix.h5',
                key: 'nbS1-HEX6-L1_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX6-L23',
            name: 'nbS1-HEX6-L23',
            description: 'Neurons in layers 2 and 3 of the hexagonal column nbS1-O1-HEX6',
            parent: 'nbS1-HEX6',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 8803,
            numberOfConnections: 1123575,
            numberOfSynapses: 5095580,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6-L23/connectivity_matrix.h5',
                key: 'nbS1-HEX6-L23_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX6-L4',
            name: 'nbS1-HEX6-L4',
            description: 'Neurons in layer 4 of the hexagonal column nbS1-O1-HEX6',
            parent: 'nbS1-HEX6',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 4902,
            numberOfConnections: 407735,
            numberOfSynapses: 2258912,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6-L4/connectivity_matrix.h5',
                key: 'nbS1-HEX6-L4_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX6-L5',
            name: 'nbS1-HEX6-L5',
            description: 'Neurons in layer 5 of the hexagonal column nbS1-O1-HEX6',
            parent: 'nbS1-HEX6',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 5878,
            numberOfConnections: 656400,
            numberOfSynapses: 5183194,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6-L5/connectivity_matrix.h5',
                key: 'nbS1-HEX6-L5_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
          {
            key: 'nbS1-HEX6-L6',
            name: 'nbS1-HEX6-L6',
            description: 'Neurons in layer 6 of the hexagonal column nbS1-O1-HEX6',
            parent: 'nbS1-HEX6',
            hasSubcircuits: false,
            brainRegion: 'Primary somatosensory area',
            species: 'Rattus norvegicus',
            numberOfNeurons: 10512,
            numberOfConnections: 1739880,
            numberOfSynapses: 8125675,
            metadata: {
              contributorSimple: 'Reimann et al and Isbister et al, EPFL ',
              contributor: 'None',
              contributingInstitution: 'EPFL ',
              registrationDate: 'November, 2024',
              revision: null,
              createdBy: 'None',
              creationDate: '27.03.2025',
              license: {
                name: 'CC-BY',
                url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
              },
            },
            files: [
              {
                kind: 'h5',
                url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX6-L6/connectivity_matrix.h5',
                key: 'nbS1-HEX6-L6_ConnectivityMatrix',
                isAvailable: true,
              },
            ],
            subcircuits: [],
            provenance: {
              isASubcircuit: false,
              subcircuitOf: null,
              literature: [],
            },
            relatedPublications: [],
            images: {
              low: null,
              normal: null,
              high: '',
            },
            overview: {
              cellStatistics: [],
              networkStatistics: [],
            },
          },
        ],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: null,
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta',
    name: 'nbS1-O1-beta',
    description:
      'Central subvolume of a first instance  of a model of the non-barrel primary somatosensory cortex of juvenile rat nbS1-01.',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457567,
    numberOfSynapses: 407127134,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta/connectivity_matrix.h5',
        key: 'nbS1-O1-beta_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta',
        name: 'nbS1-HEX0-beta',
        description:
          'Hexagonal column at the center of nbS1-O1-beta, part of a partition into seven columns.',
        parent: 'nbS1-O1-beta',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291147,
        numberOfSynapses: 41299369,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: '',
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta-ER',
    name: 'nbS1-O1-beta-ER',
    description:
      'nbS1-O1-beta, with excitatory connectivity in its central subvolume rewired to be completely random (Erd\u0151s\u2013R\u00e9nyi).',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87459908,
    numberOfSynapses: 402518201,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta-ER/connectivity_matrix.h5',
        key: 'nbS1-O1-beta-ER_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta-ER',
        name: 'nbS1-HEX0-beta-ER',
        description:
          'nbS1-HEX0-beta, with excitatory connectivity rewired to be completely random (Erd\u0151s\u2013R\u00e9nyi).',
        parent: 'nbS1-O1-beta-ER',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8293488,
        numberOfSynapses: 36690436,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta-ER/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta-ER_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: '',
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta-DD',
    name: 'nbS1-O1-beta-DD',
    description:
      'nbS1-O1-beta, with excitatory connectivity in its central subvolume rewired to be random in a distance-dependent manner.',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457566,
    numberOfSynapses: 405187752,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta-DD/connectivity_matrix.h5',
        key: 'nbS1-O1-beta-DD_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta-DD',
        name: 'nbS1-HEX0-beta-DD',
        description:
          'nbS1-HEX0-beta, with excitatory connectivity rewired to be random in a distance-dependent manner.',
        parent: 'nbS1-O1-beta-DD',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291146,
        numberOfSynapses: 39359987,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta-DD/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta-DD_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta-BIP',
    name: 'nbS1-O1-beta-BIP',
    description:
      'nbS1-O1-beta, with excitatory connectivity in its central subvolume rewired to be random in a bipolar distance-dependent manner.',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457569,
    numberOfSynapses: 406088376,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta-BIP/connectivity_matrix.h5',
        key: 'nbS1-O1-beta-BIP_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta-BIP',
        name: 'nbS1-HEX0-beta-BIP',
        description:
          'nbS1-HEX0-beta, with excitatory connectivity rewired to be random in a bipolar distance-dependent manner.',
        parent: 'nbS1-O1-beta-BIP',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291149,
        numberOfSynapses: 40260611,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta-BIP/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta-BIP_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta-OFF',
    name: 'nbS1-O1-beta-OFF',
    description:
      'nbS1-O1-beta, with excitatory connectivity in its central subvolume rewired to be random in an offset-dependent manner.',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457567,
    numberOfSynapses: 406247297,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta-OFF/connectivity_matrix.h5',
        key: 'nbS1-O1-beta-OFF_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta-OFF',
        name: 'nbS1-HEX0-beta-OFF',
        description:
          'nbS1-HEX0-beta, with excitatory connectivity rewired to be random in an offset-dependent manner.',
        parent: 'nbS1-O1-beta-OFF',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291147,
        numberOfSynapses: 40419532,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta-OFF/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta-OFF_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'nbS1-O1-beta-POS',
    name: 'nbS1-O1-beta-POS',
    description:
      'nbS1-O1-beta, with excitatory connectivity in its central subvolume rewired to be random in a position- and offset-dependent manner.',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Primary somatosensory area',
    species: 'Rattus norvegicus',
    numberOfNeurons: 211712,
    numberOfConnections: 87457567,
    numberOfSynapses: 407068355,
    metadata: {
      contributorSimple: 'Christoph Pokorny et al , EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'February, 2025',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-O1-beta-POS/connectivity_matrix.h5',
        key: 'nbS1-O1-beta-POS_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'nbS1-HEX0-beta-POS',
        name: 'nbS1-HEX0-beta-POS',
        description:
          'nbS1-HEX0-beta, with excitatory connectivity rewired to be random in a position- and offset-dependent manner.',
        parent: 'nbS1-O1-beta-POS',
        hasSubcircuits: false,
        brainRegion: 'Primary somatosensory area',
        species: 'Rattus norvegicus',
        numberOfNeurons: 30190,
        numberOfConnections: 8291147,
        numberOfSynapses: 41240590,
        metadata: {
          contributorSimple: 'Christoph Pokorny et al , EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'February, 2025',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/nbS1-HEX0-beta-POS/connectivity_matrix.h5',
            key: 'nbS1-HEX0-beta-POS_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
  {
    key: 'rCA1',
    name: 'rCA1',
    description: 'Full-scale model of rat CA1',
    parent: 'None',
    hasSubcircuits: true,
    brainRegion: 'Field CA1 ',
    species: 'Rattus norvegicus',
    numberOfNeurons: 456378,
    numberOfConnections: 156661043,
    numberOfSynapses: 820867760,
    metadata: {
      contributorSimple: 'Romani et al., EPFL ',
      contributor: 'None',
      contributingInstitution: 'EPFL ',
      registrationDate: 'November, 2024',
      revision: null,
      createdBy: 'None',
      creationDate: '27.03.2025',
      license: {
        name: 'CC-BY',
        url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
      },
    },
    files: [
      {
        kind: 'h5',
        url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/rCA1/connectivity_matrix.h5',
        key: 'rCA1_ConnectivityMatrix',
        isAvailable: true,
      },
    ],
    subcircuits: [
      {
        key: 'rCA1-SLICE-REF',
        name: 'rCA1-SLICE-REF',
        description: 'Slice extracted from CA1 of 400 um thickness with projections.',
        parent: 'rCA1',
        hasSubcircuits: false,
        brainRegion: 'Field CA2',
        species: 'Rattus norvegicus',
        numberOfNeurons: 17647,
        numberOfConnections: 4532541,
        numberOfSynapses: 24530144,
        metadata: {
          contributorSimple: 'Romani et al., EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/rCA1-SLICE-REF/connectivity_matrix.h5',
            key: 'rCA1-SLICE-REF_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
      {
        key: 'rCA1-CYLINDER-REF',
        name: 'rCA1-CYLINDER-REF',
        description: 'Cylinder extracted from CA1 of 300 um diameter with projections.',
        parent: 'rCA1',
        hasSubcircuits: false,
        brainRegion: 'Field CA3',
        species: 'Rattus norvegicus',
        numberOfNeurons: 6213,
        numberOfConnections: 1236142,
        numberOfSynapses: 7115120,
        metadata: {
          contributorSimple: 'Romani et al., EPFL ',
          contributor: 'None',
          contributingInstitution: 'EPFL ',
          registrationDate: 'November, 2024',
          revision: null,
          createdBy: 'None',
          creationDate: '27.03.2025',
          license: {
            name: 'CC-BY',
            url: 'https://creativecommons.org/licenses/by/4.0/legalcode',
          },
        },
        files: [
          {
            kind: 'h5',
            url: 'https://openbluebrain.s3.us-west-2.amazonaws.com/Simulatable_Circuit/ConnectivityMatrices/rCA1-CYLINDER-REF/connectivity_matrix.h5',
            key: 'rCA1-CYLINDER-REF_ConnectivityMatrix',
            isAvailable: true,
          },
        ],
        subcircuits: [],
        provenance: {
          isASubcircuit: false,
          subcircuitOf: null,
          literature: [],
        },
        relatedPublications: [],
        images: {
          low: null,
          normal: null,
          high: '',
        },
        overview: {
          cellStatistics: [],
          networkStatistics: [],
        },
      },
    ],
    provenance: {
      isASubcircuit: false,
      subcircuitOf: null,
      literature: [],
    },
    relatedPublications: [],
    images: {
      low: null,
      normal: null,
      high: null,
    },
    overview: {
      cellStatistics: [],
      networkStatistics: [],
    },
  },
];

export default HARD_CODED_CONTENT;
