const singleCaseQuery = (slug: string) =>
  `*[_type == "publicProjects" && slug.current == "${slug}"][0] {
        name,
        'slug': slug.current,
        introduction,
        'heroImage': heroImage.asset->url,
        authorsList[] {
            firstName,
            lastName,
            email,
            institution
        },
        description,
        videosList[] {
            url,
            title,
            alt,
            hasCaption,
            useTimestamps,
            'captionTrack': captionTrack.asset->url
        },
        artifactType[],
        artifact[] {
            title, 
            description,
            "file": file.asset->url,
            url,
            _type,
        },
        meModelsList[] {
            'file': file.asset->url,
            name,
            hasMorphologyThumbnail,
            "morphology": morphology.asset->url,
            hasTraceThumbnail,
            "trace": trace.asset->url,
            validated,
            brainRegion,
            species,
            mType,
            eType,
            createdBy,
            creationDate,
            morphologyId,
            traceFileId,
            url,
            _type,
        },
        minimalMeModel[] {
            name,
            brainRegion,
            mType,
            eType,
            species,
        },
        eModelsList[] {
            name,
            hasResponseThumbnail,
            'response': response.asset->url,
            brainRegion,
            mType,
            eType,
            morphologyName,
            modelCumulatedScore,
            species,
            validated,
            contributor,
            creationDate,
        },
        notebook[] {
            name,
            readMe,
            url,
            objectOfInterest,
            scale,
            authors,
            creationDate,
        },
         _updatedAt,
    }`;

export default singleCaseQuery;
