import { SingleSectionProps } from '../type';

import { useAITools } from '@/services/ai-agent/tools/tools';

export function useDocumentationArchitecture(): SingleSectionProps[] {
  const tools = useAITools() ?? [];

  return [
    {
      name: 'Overview',
      slug: 'overview',
      children: null,
      disabled: false,
      link: '/app/documentation',
    },
    {
      name: 'Ontology',
      slug: 'ontology',
      children: null,
      disabled: true,
      link: '/app/documentation/ontology',
    },
    {
      name: 'Your virtual lab',
      slug: 'virtual-lab',
      children: null,
      disabled: true,
      link: '/app/documentation/virtual-lab',
    },
    {
      name: 'Projects',
      slug: 'projects',
      children: null,
      disabled: true,
      link: '/app/documentation/projects',
    },
    {
      name: 'Notebooks',
      slug: 'notebooks',
      children: null,
      disabled: true,
      link: '/app/documentation/notebooks',
    },
    {
      name: 'Explore',
      slug: 'explore',
      children: null,
      disabled: true,
      link: '/app/documentation/explore',
    },
    {
      name: 'AI Chat tools',
      slug: 'ai-chat-tools',
      children: tools.map((tool) => ({
        name: tool.name,
        slug: tool.id,
        children: null,
        disabled: false,
        link: `/app/documentation/ai-chat-tools/${tool.id}`,
      })),
      link: '/app/documentation/ai-chat-tools',
      disabled: false,
    },
    {
      name: 'Build',
      slug: 'build',
      children: [
        {
          name: 'Ion Channels',
          slug: 'ion-channels',
          children: null,
          link: '/app/documentation/build/ion-channels',
          disabled: false,
        },
        {
          name: 'Metabolism',
          slug: 'metabolism',
          children: null,
          link: '/app/documentation/build/metabolism',
          disabled: false,
        },
        {
          name: 'NGV Unit',
          slug: 'ngv-unit',
          children: null,
          link: '/app/documentation/build/ngv-unit',
          disabled: false,
        },
        {
          name: 'Single Neuron',
          slug: 'single-neuron',
          children: null,
          link: '/app/documentation/build/single-neuron',
          disabled: false,
        },
        {
          name: 'Synaptome',
          slug: 'synaptome',
          children: null,
          link: '/app/documentation/build/synaptome',
          disabled: false,
        },
        {
          name: 'Paired Neurons',
          slug: 'paired-neurons',
          children: null,
          link: '/app/documentation/build/paired-neurons',
          disabled: false,
        },
        {
          name: 'Small microcircuits',
          slug: 'small-microcircuits',
          children: null,
          link: '/app/documentation/build/small-microcircuits',
          disabled: false,
        },
        {
          name: 'Microcircuits',
          slug: 'microcircuits',
          children: null,
          link: '/app/documentation/build/microcircuits',
          disabled: false,
        },
        {
          name: 'NGV Circuit',
          slug: 'ngv-circuit',
          children: null,
          link: '/app/documentation/build/ngv-circuit',
          disabled: false,
        },
        {
          name: 'Brain Region',
          slug: 'brain-region',
          children: null,
          link: '/app/documentation/build/brain-region',
          disabled: false,
        },
        {
          name: 'Brain System',
          slug: 'brain-system',
          children: null,
          link: '/app/documentation/build/brain-system',
          disabled: false,
        },
        {
          name: 'Whole Brain',
          slug: 'whole-brain',
          children: null,
          link: '/app/documentation/build/whole-brain',
          disabled: false,
        },
      ],
      link: '/app/documentation/build',
      disabled: true,
    },
    {
      name: 'Experiment',
      slug: 'experiment',
      children: [
        {
          name: 'Ion Channels',
          slug: 'ion-channels',
          children: null,
          link: '/app/documentation/experiment/ion-channels',
          disabled: false,
        },
        {
          name: 'Metabolism',
          slug: 'metabolism',
          children: null,
          link: '/app/documentation/experiment/metabolism',
          disabled: false,
        },
        {
          name: 'NGV Unit',
          slug: 'ngv-unit',
          children: null,
          link: '/app/documentation/experiment/ngv-unit',
          disabled: false,
        },
        {
          name: 'Single Neuron',
          slug: 'single-neuron',
          children: null,
          link: '/app/documentation/experiment/single-neuron',
          disabled: false,
        },
        {
          name: 'Synaptome',
          slug: 'synaptome',
          children: null,
          link: '/app/documentation/experiment/synaptome',
          disabled: false,
        },
        {
          name: 'Paired Neurons',
          slug: 'paired-neurons',
          children: null,
          link: '/app/documentation/experiment/paired-neurons',
          disabled: false,
        },
        {
          name: 'Small microcircuits',
          slug: 'small-microcircuits',
          children: null,
          link: '/app/documentation/experiment/small-microcircuits',
          disabled: false,
        },
        {
          name: 'Microcircuits',
          slug: 'microcircuits',
          children: null,
          link: '/app/documentation/experiment/microcircuits',
          disabled: false,
        },
        {
          name: 'NGV Circuit',
          slug: 'ngv-circuit',
          children: null,
          link: '/app/documentation/experiment/ngv-circuit',
          disabled: false,
        },
        {
          name: 'Brain Region',
          slug: 'brain-region',
          children: null,
          link: '/app/documentation/experiment/brain-region',
          disabled: false,
        },
        {
          name: 'Brain System',
          slug: 'brain-system',
          children: null,
          link: '/app/documentation/experiment/brain-system',
          disabled: false,
        },
        {
          name: 'Whole Brain',
          slug: 'whole-brain',
          children: null,
          link: '/app/documentation/experiment/whole-brain',
          disabled: false,
        },
      ],
      link: '/app/documentation/experiment',
      disabled: true,
    },
  ];
}
