import { EntityCoreFields } from '@/entity-configuration/definitions/fields-defs/enums';
import { ExtendedEntitiesTypeDict } from '@/api/entitycore/types/extended-entity-type';
import { DataTypeGroup } from '@/entity-configuration/definitions/view-defs/types';
import { EntitySlug } from '@/entity-configuration/domain/slug';

import type { ViewDefinitionConfig } from '@/entity-configuration/definitions/view-defs/types';

export const ViewsDefinition: { [key: string]: ViewDefinitionConfig } = {
  [ExtendedEntitiesTypeDict.CellMorphology]: {
    title: 'Morphology',
    group: DataTypeGroup.ExperimentalData,
    name: EntitySlug.CellMorphology,
    columns: [
      EntityCoreFields.Preview,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.MType,
      EntityCoreFields.Name,
      EntityCoreFields.Species,
      EntityCoreFields.Contributions,
      EntityCoreFields.RegistrationDate,
    ],
    curated: true,
    cardViewFields: [
      {
        field: EntityCoreFields.Name,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.NeuronMorphologyWidth,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.NeuronMorphologyHeight,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.NeuronMorphologyDepth,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.AxonTotalLength,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.AxonStrahlerNumber,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.AxonArborAsymmetryIndex,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.BasalDendriticTotalLength,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.BasalDendriteStrahlerNumber,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.BasalArborAsymmetryIndex,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.ApicalDendriticTotalLength,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.ApicalDendtriteStrahlerNumber,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.SomaDiameter,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.ApicalArborAsymmetryIndex,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.BrainRegion,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.MType,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.Species,
        className: 'col-span-2',
      },
      {
        field: EntityCoreFields.Contributions,
        className: 'col-span-2',
      },
    ],
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.MType },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.License },
    ],
    mlTopic: 'Neuron morphology',
  },
  [ExtendedEntitiesTypeDict.ElectricalCellRecording]: {
    title: 'Electrophysiology',
    group: DataTypeGroup.ExperimentalData,
    name: EntitySlug.ElectricalCellRecording,
    columns: [
      EntityCoreFields.Preview,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.EType,
      EntityCoreFields.Name,
      EntityCoreFields.Species,
      EntityCoreFields.Contributions,
      EntityCoreFields.RegistrationDate,
    ],
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.SubjectAge },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
    ],
    curated: true,
    mlTopic: 'Neuron spike',
  },
  [ExtendedEntitiesTypeDict.ExperimentalNeuronDensity]: {
    title: 'Neuron density',
    group: DataTypeGroup.ExperimentalData,
    name: EntitySlug.ExperimentalNeuronDensity,
    columns: [
      EntityCoreFields.BrainRegion,
      EntityCoreFields.MType,
      EntityCoreFields.EType,
      EntityCoreFields.NeuronDensity,
      EntityCoreFields.NumberOfMeasurements,
      EntityCoreFields.Name,
      EntityCoreFields.Species,
      EntityCoreFields.SubjectAge,
      EntityCoreFields.Contributions,
      EntityCoreFields.RegistrationDate,
    ],
    cardViewFields: [
      { field: EntityCoreFields.Name, className: 'col-span-2' },
      { field: EntityCoreFields.NeuronMorphologyWidth, className: 'col-span-2' },
      { field: EntityCoreFields.NeuronMorphologyHeight, className: 'col-span-2' },
      { field: EntityCoreFields.NeuronMorphologyDepth, className: 'col-span-2' },
      { field: EntityCoreFields.AxonTotalLength, className: 'col-span-2' },
      { field: EntityCoreFields.AxonStrahlerNumber, className: 'col-span-2' },
      { field: EntityCoreFields.AxonArborAsymmetryIndex, className: 'col-span-2' },
      { field: EntityCoreFields.BasalDendriticTotalLength, className: 'col-span-2' },
      { field: EntityCoreFields.BasalDendriteStrahlerNumber, className: 'col-span-2' },
      { field: EntityCoreFields.BasalArborAsymmetryIndex, className: 'col-span-2' },
      { field: EntityCoreFields.ApicalDendriticTotalLength, className: 'col-span-2' },
      { field: EntityCoreFields.ApicalDendtriteStrahlerNumber, className: 'col-span-2' },
      { field: EntityCoreFields.SomaDiameter, className: 'col-span-2' },
      { field: EntityCoreFields.ApicalArborAsymmetryIndex, className: 'col-span-2' },
      { field: EntityCoreFields.BrainRegion, className: 'col-span-2' },
      { field: EntityCoreFields.MType, className: 'col-span-2' },
      { field: EntityCoreFields.Species, className: 'col-span-2' },
      { field: EntityCoreFields.Contributions, className: 'col-span-2' },
    ],
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.SubjectAge },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.NeuronDensity },
      { field: EntityCoreFields.NumberOfMeasurements },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.License, className: 'col-start-2 row-start-3' },
    ],
    curated: false,
    mlTopic: 'cell composition',
  },
  [ExtendedEntitiesTypeDict.ExperimentalBoutonDensity]: {
    title: 'Bouton density',
    group: DataTypeGroup.ExperimentalData,
    name: EntitySlug.ExperimentalBoutonDensity,
    columns: [
      EntityCoreFields.BrainRegion,
      EntityCoreFields.MType,
      EntityCoreFields.MeanSTD,
      EntityCoreFields.Sem,
      EntityCoreFields.NumberOfMeasurements,
      EntityCoreFields.Species,
      EntityCoreFields.Contributions,
    ],
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.SubjectAge },
      { field: EntityCoreFields.MeanSTD },
      { field: EntityCoreFields.Weight },
      { field: EntityCoreFields.Sem },
      { field: EntityCoreFields.NumberOfMeasurements },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.License },
    ],
    curated: false,
    mlTopic: 'Bouton density',
  },
  [ExtendedEntitiesTypeDict.ExperimentalSynapsesPerConnection]: {
    title: 'Synapse per connection',
    group: DataTypeGroup.ExperimentalData,
    name: EntitySlug.ExperimentalSynapsesPerConnection,
    columns: [
      EntityCoreFields.PreSynapticBrainRegion,
      EntityCoreFields.PostSynapticBrainRegion,
      EntityCoreFields.PreSynapticCellType,
      EntityCoreFields.PostSynapticCellType,
      EntityCoreFields.MeanSTD,
      EntityCoreFields.Species,
      EntityCoreFields.SubjectAge,
      EntityCoreFields.Contributions,
    ],
    summaryViewFields: [
      { field: EntityCoreFields.PreSynapticBrainRegion },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.PostSynapticBrainRegion },
      { field: EntityCoreFields.SubjectAge },
      { field: EntityCoreFields.PreSynapticCellType },
      { field: EntityCoreFields.Weight },
      { field: EntityCoreFields.PostSynapticCellType },
      { field: EntityCoreFields.MeanSTD },
      { field: EntityCoreFields.Sem },
      // {
      //   field: EntityCoreFields.NumberOfConnections,
      // },
    ],
    miniDetailView: [
      { field: EntityCoreFields.PreSynapticBrainRegion },
      { field: EntityCoreFields.PostSynapticBrainRegion },
      { field: EntityCoreFields.PreSynapticCellType },
      { field: EntityCoreFields.PostSynapticCellType },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.SubjectAge },
      { field: EntityCoreFields.License },
    ],
    curated: false,
    mlTopic: 'Synapse per connection',
  },
};
