import { EntityCoreFields } from '@/entity-configuration/definitions/fields-defs/enums';
import { DataTypeGroup } from '@/entity-configuration/definitions/view-defs/types';
import { ExtendedEntitiesTypeDict } from '@/api/entitycore/types/extended-entity-type';
import { EntitySlug } from '@/entity-configuration/domain/slug';

import type { ViewDefinitionConfig } from '@/entity-configuration/definitions/view-defs/types';

export const ViewsDefinition: { [key: string]: ViewDefinitionConfig } = {
  [ExtendedEntitiesTypeDict.Emodel]: {
    title: 'E-model',
    group: DataTypeGroup.ModelData,
    name: EntitySlug.EModel,
    columns: [
      EntityCoreFields.Name,
      EntityCoreFields.EModelResponse,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.MType,
      EntityCoreFields.EType,
      EntityCoreFields.EModelExemplarMorphology,
      EntityCoreFields.EModelScore,
      EntityCoreFields.Contributions,
      EntityCoreFields.CreationDate,
    ],
    curated: true,
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.EModelScore },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.EModelScore },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.RegistrationDate },
      { field: EntityCoreFields.License },
    ],
  },
  [ExtendedEntitiesTypeDict.Memodel]: {
    title: 'ME-model',
    group: DataTypeGroup.ModelData,
    name: EntitySlug.MeModel,
    columns: [
      EntityCoreFields.Name,
      EntityCoreFields.MEModelMorphologyPreview,
      EntityCoreFields.MEModelTracePreview,
      EntityCoreFields.MEModelValidationStatus,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.MType,
      EntityCoreFields.EType,
      EntityCoreFields.CreatedBy,
      EntityCoreFields.CreationDate,
    ],
    curated: false,
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.MEModelValidationStatus },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.MEModelValidationStatus },
      { field: EntityCoreFields.RegistrationDate },
      { field: EntityCoreFields.License },
    ],
  },
  [ExtendedEntitiesTypeDict.SingleNeuronSynaptome]: {
    title: 'Synaptome',
    group: DataTypeGroup.ModelData,
    name: EntitySlug.SingleNeuronSynaptome,
    columns: [
      EntityCoreFields.Name,
      EntityCoreFields.Description,
      EntityCoreFields.SynaptomeUsedMEModelName,
      EntityCoreFields.MType,
      EntityCoreFields.EType,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.CreatedBy,
      EntityCoreFields.CreationDate,
    ],
    curated: false,
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.License },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.SynaptomeUsedMEModelName },
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.SynaptomeUsedMEModelName },
      { field: EntityCoreFields.MType },
      { field: EntityCoreFields.EType },
      { field: EntityCoreFields.RegistrationDate },
      { field: EntityCoreFields.License },
    ],
  },
  [ExtendedEntitiesTypeDict.Circuit]: {
    title: 'Circuit',
    name: EntitySlug.Circuit,
    curated: false,
    columns: [
      EntityCoreFields.Download,
      EntityCoreFields.Name,
      EntityCoreFields.CircuitSubCircuit,
      EntityCoreFields.Description,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.CircuitScale,
      EntityCoreFields.CircuitNumberNeurons,
      EntityCoreFields.CircuitNumberSynapses,
      EntityCoreFields.CircuitNumberConnections,
      EntityCoreFields.Species,
      EntityCoreFields.CircuitBuildCategory,
      EntityCoreFields.CircuitPublishedIn,
      EntityCoreFields.CircuitExperimentDate,
    ],
    miniDetailView: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.CircuitScale },
      { field: EntityCoreFields.Species },
      { field: EntityCoreFields.CircuitSubCircuit },
      { field: EntityCoreFields.CircuitNumberNeurons },
      { field: EntityCoreFields.CircuitNumberSynapses },
      { field: EntityCoreFields.CircuitNumberConnections },
      { field: EntityCoreFields.CircuitBuildCategory },
      { field: EntityCoreFields.RegistrationDate },
      { field: EntityCoreFields.License },
    ],
    summaryViewFields: [
      { field: EntityCoreFields.BrainRegion },
      { field: EntityCoreFields.CircuitRootCircuit },
      { field: EntityCoreFields.CircuitScale },
      { field: EntityCoreFields.License },
      {
        field: EntityCoreFields.CircuitNumberNeurons,
      },
      {
        field: EntityCoreFields.CircuitNumberConnections,
      },
      {
        field: EntityCoreFields.CircuitNumberSynapses,
      },
      {
        field: EntityCoreFields.CircuitPublishedIn,
      },
      {
        field: EntityCoreFields.CircuitExperimentDate,
      },
      {
        field: EntityCoreFields.CircuitContactEmail,
      },
    ],
  },
  [ExtendedEntitiesTypeDict.SmallMicrocircuit]: {
    title: 'Small microcircuit',
    name: EntitySlug.SmallMicrocircuit,
    curated: false,
    columns: [
      EntityCoreFields.Name,
      EntityCoreFields.Description,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.CircuitNumberNeurons,
      EntityCoreFields.CircuitNumberSynapses,
      EntityCoreFields.CircuitNumberConnections,
      EntityCoreFields.CreatedBy,
      EntityCoreFields.CreationDate,
    ],
  },
  [ExtendedEntitiesTypeDict.PairedNeuronCircuit]: {
    title: 'Paired neurons',
    name: EntitySlug.PairedNeuronsCircuit,
    curated: false,
    columns: [
      EntityCoreFields.Name,
      EntityCoreFields.Description,
      EntityCoreFields.BrainRegion,
      EntityCoreFields.CircuitNumberNeurons,
      EntityCoreFields.CircuitNumberSynapses,
      EntityCoreFields.CircuitNumberConnections,
      EntityCoreFields.CreatedBy,
      EntityCoreFields.CreationDate,
    ],
  },
};
