import { z } from 'zod';

export const serverSchema = z.object({
  KEYCLOAK_ISSUER: z.string().url(),
  KEYCLOAK_CLIENT_ID: z.string().min(3),
  KEYCLOAK_CLIENT_SECRET: z.string().min(5),
  NEXTAUTH_SECRET: z.string().min(5),
  MAILCHIMP_API_KEY: z.string().min(1),
  MAILCHIMP_AUDIENCE_ID: z.string().min(1),
  MAILCHIMP_API_SERVER: z.string().min(1),
  GITHUB_TOKEN: z.string().optional(),
  AUTH_MANAGER_URI: z.string().url().optional(),

  BASE_PATH: z.preprocess((basePath) => basePath ?? '', z.string()),
  CDN_URI: z.string().url().optional(),
  SENTRY_DSN: z.preprocess((sentryDsn) => sentryDsn || undefined, z.string().url().optional()),
  SENTRY_ORG: z.string().optional(),
  SENTRY_PRJ: z.string().optional(),
  ACCOUNTING_BASE_URL: z.string().url().optional(),
  SMALL_SCALE_SIMULATOR_URL: z.string().url(),
  CELL_SVC_BASE_URL: z.string().url(),
  THUMBNAIL_GENERATION_BASE_URL: z.string().url(),
  VIRTUAL_LAB_API_URL: z.string().url(),
  STRIPE_PUBLISHABLE_KEY: z.string().startsWith('pk_'),
  DEPLOYMENT_ENV: z.enum(['local', 'preview', 'development', 'staging', 'production']),
  MATOMO_URL: z.string().optional(),
  MATOMO_CDN_URL: z.string().optional(),
  MATOMO_SITE_ID: z.string().optional(),
  SANITY_DATASET: z.enum(['staging', 'production']),
  ENTITY_CORE_URL: z.string().url(),
  ENTITY_CORE_PUBLIC_VIRTUAL_LAB_ID: z.string().nonempty(),
  ENTITY_CORE_PUBLIC_PROJECT_ID: z.string().nonempty(),
  DEFAULT_BRAIN_REGION_HIERARCHY_ID: z.string().nonempty(),
  DEFAULT_SELECTED_BRAIN_REGION_ID: z.string().nonempty(),
  BASIC_CELL_GROUPS_AND_REGIONS_BRAIN_REGION_ANNOTATION_VALUE: z.string().nonempty(),
  DEFAULT_BRAIN_ATLAS_ID: z.string().nonempty(),
  ROOT_BRAIN_REGION_ANNOTATION_VALUE: z.string().nonempty(),
  ROOT_BRAIN_REGION_ID: z.string().nonempty(),
  LEGACY_DEFAULT_CIRCUIT_ID: z.string().url().optional(),
  CORE_WEB_APP_VERSION: z.string().optional(),
  NOTEBOOK_SERVICE_BASE_URL: z.string().optional(),
  OBI_ONE_URL: z.string().nonempty(),
  AI_AGENT_URL: z.string().url().optional(),
  ROOT_ROUTE: z.string(),
  NOTEBOOK_REPO_URL: z.string().url(),
});

// ! WARNING: clientSchema configurations are exposed in the browser.
// ! Only add configurations that are safe to be public. NO SECRETS.
export const clientSchema = serverSchema.pick({
  BASE_PATH: true,
  CDN_URI: true,
  SENTRY_DSN: true,
  SENTRY_ORG: true,
  SENTRY_PRJ: true,
  ACCOUNTING_BASE_URL: true,
  SMALL_SCALE_SIMULATOR_URL: true,
  CELL_SVC_BASE_URL: true,
  THUMBNAIL_GENERATION_BASE_URL: true,
  VIRTUAL_LAB_API_URL: true,
  STRIPE_PUBLISHABLE_KEY: true,
  DEPLOYMENT_ENV: true,
  MATOMO_URL: true,
  MATOMO_CDN_URL: true,
  MATOMO_SITE_ID: true,
  SANITY_DATASET: true,
  ENTITY_CORE_URL: true,
  ENTITY_CORE_PUBLIC_VIRTUAL_LAB_ID: true,
  ENTITY_CORE_PUBLIC_PROJECT_ID: true,
  DEFAULT_BRAIN_REGION_HIERARCHY_ID: true,
  DEFAULT_SELECTED_BRAIN_REGION_ID: true,
  BASIC_CELL_GROUPS_AND_REGIONS_BRAIN_REGION_ANNOTATION_VALUE: true,
  DEFAULT_BRAIN_ATLAS_ID: true,
  ROOT_BRAIN_REGION_ANNOTATION_VALUE: true,
  ROOT_BRAIN_REGION_ID: true,
  LEGACY_DEFAULT_CIRCUIT_ID: true,
  CORE_WEB_APP_VERSION: true,
  NOTEBOOK_SERVICE_BASE_URL: true,
  OBI_ONE_URL: true,
  AUTH_MANAGER_URI: true,
  AI_AGENT_URL: true,
  ROOT_ROUTE: true,
  NOTEBOOK_REPO_URL: true,
});

export type ServerConfig = z.infer<typeof serverSchema>;
export type ClientConfig = z.infer<typeof clientSchema>;
