export enum CoreFieldFilterTypeEnum {
  WithinList = 'WithinList',
  CheckList = 'CheckList',
  DateRange = 'DateRange',
  Search = 'Search',
  Text = 'Text',
  ValueOrRange = 'ValueOrRange',
  ValueRange = 'ValueRange',
  DropdownList = 'DropdownList',
}

export enum EntityCoreFields {
  ID = 'id',
  Preview = 'preview',
  Download = 'download',
  Name = 'name',
  Description = 'description',
  Species = 'species',
  CreationDate = 'creation_date',
  RegistrationDate = 'registration_date',
  UpdateDate = 'update_date',
  Contributions = 'contribution',
  InstitutionalContributions = 'institutional_contributions',
  License = 'license',
  BrainRegion = 'brain_region',
  MType = 'mtype',
  EType = 'etype',
  NeuronDensity = 'neuron_density', // TODO: to check new naming
  NumberOfMeasurements = 'number_of_measurements', // TODO: to check new naming
  SubjectAge = 'subject_age', // TODO: to check new naming
  Sem = 'sem', // TODO: to check new naming
  MeanSTD = 'meanstd', // TODO: to check new naming
  NeuronMorphologyWidth = 'neuronMorphologyWidth',
  NeuronMorphologyHeight = 'NeuronMorphologyHeight',
  NeuronMorphologyDepth = 'neuronMorphologyDepth',
  AxonTotalLength = 'axonTotalLength',
  AxonStrahlerNumber = 'axonStrahlerNumber',
  AxonArborAsymmetryIndex = 'axonArborAsymmetryIndex',
  BasalDendriticTotalLength = 'basalDendriticTotalLength',
  BasalDendriteStrahlerNumber = 'basalDendriteStrahlerNumber',
  BasalArborAsymmetryIndex = 'basalArborAsymmetryIndex',
  ApicalDendriticTotalLength = 'apicalDendriticTotalLength',
  ApicalDendtriteStrahlerNumber = 'apicalDendtriteStrahlerNumber',
  SomaDiameter = 'somaDiameter',
  ApicalArborAsymmetryIndex = 'apicalArborAsymmetryIndex',
  PreSynapticBrainRegion = 'pre_region',
  PostSynapticBrainRegion = 'post_region',
  PreSynapticCellType = 'pre_mtype',
  PostSynapticCellType = 'post_mtype',
  Weight = 'weight',
  EModelExemplarMorphology = 'exemplar_morphology',
  EModelScore = 'eModelScore',
  EModelResponse = 'eModelResponse',
  MEModelMorphologyPreview = 'meModelMorphologyPreview',
  MEModelTracePreview = 'meModelTracePreview',
  MEModelValidationStatus = 'validation_status',
  SynaptomeUsedMEModelName = 'me_model',
  SynaptomeModelName = 'synaptome',
  CreatedBy = 'created_by',
  UpdatedBy = 'updated_by',
  SimulationSeed = 'simulation_seed',
  InjectionLocation = 'injection_location',
  RecordingLocation = 'recording_location',
  SimulationStatus = 'simulation_status',
  SimulationResponse = 'simulation_response',
  SimulationStimulus = 'simulation_stimulus',
  SimulationModel = 'me_model',
  CircuitNumberNeurons = 'number_neurons',
  CircuitNumberSynapses = 'number_synapses',
  CircuitNumberConnections = 'number_connections',
  ScanParameters = 'scan_parameters',
  SimulationCampaignStatus = 'status',
  CircuitName = 'circuit_name',
  CircuitBuildCategory = 'build_category',
  CircuitScale = 'scale',
  CircuitRootCircuit = 'root_circuit_id', // TODO: change it to sub_circuits, this is only for test the nested table
  CircuitPublishedIn = 'published_in', // TODO: change it to sub_circuits, this is only for test the nested table
  CircuitContactEmail = 'contact_email', // TODO: change it to sub_circuits, this is only for test the nested table
  CircuitExperimentDate = 'experiment_date', // TODO: change it to sub_circuits, this is only for test the nested table
  CircuitSubCircuit = 'xxxxx', // TODO: change it to sub_circuits, this is only for test the nested table
}

export type EntityCoreFieldsValue = `${EntityCoreFields}`;
