name: Deploy to STAGING

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract commit SHA
        id: extract_version
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          echo "version=${COMMIT_SHA}" >> $GITHUB_OUTPUT
          echo "Using version: ${COMMIT_SHA}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLICECR_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLICECR_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build a Docker image
        run: |
          docker build \
            --build-arg APP_VERSION=${{ steps.extract_version.outputs.version }} \
            -t ${{ vars.PUBLICECR_URI }}:staging .

      - name: Publish To AWS ECR
        run: |
          docker push ${{ vars.PUBLICECR_URI }}:staging

      - name: Extract static assets from Docker image
        run: |
          # remove directory for extracted assets
          rm -rf ./assets-for-s3

          # create directory for extracted assets with versioned paths
          mkdir -p ./assets-for-s3/${{ steps.extract_version.outputs.version }}/public
          mkdir -p ./assets-for-s3/${{ steps.extract_version.outputs.version }}/_next

          # create temporary container and extract static assets
          docker create --name assets-extractor ${{ vars.PUBLICECR_URI }}:staging
          docker cp assets-extractor:/app/.next/static ./assets-for-s3/${{ steps.extract_version.outputs.version }}/_next/static/
          docker cp assets-extractor:/app/public ./assets-for-s3/${{ steps.extract_version.outputs.version }}/public/
          docker rm assets-extractor

      - name: Sync static assets to S3 and invalidate CloudFront
        run: |
          # upload extracted static assets to S3 with versioned paths
          aws s3 sync ./assets-for-s3/${{ steps.extract_version.outputs.version }}/public s3://${{ vars.STAGING_S3_BUCKET_NAME }}/${{ steps.extract_version.outputs.version }}/public --delete --exact-timestamps --cache-control "public, max-age=604800, immutable"
          aws s3 sync ./assets-for-s3/${{ steps.extract_version.outputs.version }}/_next/static s3://${{ vars.STAGING_S3_BUCKET_NAME }}/${{ steps.extract_version.outputs.version }}/_next/static --delete --exact-timestamps --cache-control "public, max-age=604800, immutable"

          # this need to be checked how to invalidate history
          # # invalidate CloudFront distribution
          # if [ -n "${{ vars.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
          #   aws cloudfront create-invalidation --distribution-id ${{ vars.STAGING_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/${{ steps.extract_version.outputs.version }}/*"
          # fi

      - name: Authenticate with AWS ECS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_STAGING_ECS_REDEPLOY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_STAGING_REGION }}

      - name: Trigger new deployment
        run: |
          aws ecs update-service \
            --cluster ${{ vars.AWS_STAGING_ECS_CLUSTER }} \
            --service ${{ vars.AWS_STAGING_ECS_SERVICE }} \
            --force-new-deployment

      - name: Wait until the service is stable
        run: |
          aws ecs wait services-stable \
            --cluster ${{ vars.AWS_STAGING_ECS_CLUSTER }} \
            --service ${{ vars.AWS_STAGING_ECS_SERVICE }}
