name: Publish STAGING image for Azure deployment

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-staging-azure:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PUBLICECR_UPLOAD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PUBLICECR_UPLOAD_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PUBLICECR_REGION }}

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build a Docker image for Azure
        run: |
          docker build --build-arg DEPLOYMENT_ENV=staging-azure -t ${{ vars.PUBLICECR_URI }}:staging-azure .

      - name: Publish the image for Azure To AWS ECR
        run: |
          docker push ${{ vars.PUBLICECR_URI }}:staging-azure
