name: Make release

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ vars.PUBLICECR_URI }}
    steps:
      - name: Fail if branch is not main
        if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on a branch other than main"
          exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get full history to check existing tags

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine new tag
        id: tag
        run: |
          YEAR=$(date +'%Y')
          MONTH=$(date +'%m')
          DAY=$(date +'%d')
          LATEST_TAG=$(git tag --sort=-v:refname | grep -E "^${YEAR}\.${MONTH}\.${DAY}\.[0-9]+$" | head -n 1 || echo "")

          if [[ -z "$LATEST_TAG" ]]; then
            COUNTER=1
          else
            COUNTER=$(( ${LATEST_TAG##*.} + 1 ))
          fi

          NEW_TAG="${YEAR}.${MONTH}.${DAY}.${COUNTER}"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          echo "New tag: $NEW_TAG"

      - name: Create Git Tag
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Extract version
        run: |
          APP_VERSION=$(make version)
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "Using app version: ${APP_VERSION}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.PUBLICECR_UPLOAD_ROLE_ARN }}
          aws-region: us-east-1

      - name: Authenticate with AWS Public ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build and publish Docker image for AWS
        run: make publish
